name: Update gist with TypeRacer stats
on:
  schedule:
    - cron: "0 * * * *" # hourly
  push:
    branches: master # on push
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn install
      - name: Update gist
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: decfe89a5e2ebf8e5153162a3b3f36fb
          TR_USERNAME: ${{ secrets.TR_USERNAME }}
